# Generated by Django 2.2.1 on 2019-07-07 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ACTIVITY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityName', models.CharField(max_length=50)),
                ('activityCost', models.IntegerField(default=-2147483647)),
                ('image', models.ImageField(upload_to='allImages/')),
            ],
        ),
        migrations.CreateModel(
            name='CITY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityName', models.CharField(max_length=200)),
                ('longitude', models.CharField(blank=True, max_length=30)),
                ('latitude', models.CharField(blank=True, max_length=30)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(upload_to='allImages/')),
            ],
        ),
        migrations.CreateModel(
            name='GROUP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HOTEL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotelName', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='allImages/')),
                ('longitude', models.CharField(blank=True, max_length=30)),
                ('latitude', models.CharField(blank=True, max_length=30)),
                ('cityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.CITY')),
            ],
        ),
        migrations.CreateModel(
            name='PREFERENCE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefName', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='allImages/')),
            ],
        ),
        migrations.CreateModel(
            name='PROFILE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('userName', models.CharField(max_length=50)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(blank=True, max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=50)),
                ('image', models.ImageField(default='noimage.jpg', upload_to='allImages/')),
                ('about', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('isGuide', models.CharField(blank=True, max_length=50)),
                ('cityID', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='database.CITY')),
            ],
        ),
        migrations.CreateModel(
            name='SPOT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotName', models.CharField(max_length=75)),
                ('spotInfo', models.CharField(max_length=2000)),
                ('longitude', models.CharField(blank=True, max_length=30)),
                ('latitude', models.CharField(blank=True, max_length=30)),
                ('totalVisitTime', models.CharField(blank=True, max_length=30)),
                ('openTime', models.CharField(blank=True, max_length=30)),
                ('closeTime', models.CharField(blank=True, max_length=30)),
                ('image', models.ImageField(upload_to='allImages/')),
                ('cityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.CITY')),
            ],
        ),
        migrations.CreateModel(
            name='TOURINFO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('dailyTravelTime', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('finished', models.IntegerField(default=0)),
                ('groupID', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='database.GROUP')),
                ('userID', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='database.PROFILE')),
            ],
        ),
        migrations.CreateModel(
            name='TOURINFOSPOT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.SPOT')),
                ('tourID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.TOURINFO')),
            ],
        ),
        migrations.CreateModel(
            name='TOURINFOPREFERENCE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferenceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.PREFERENCE')),
                ('tourID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.TOURINFO')),
            ],
        ),
        migrations.CreateModel(
            name='TOURINFOGROUP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.GROUP')),
                ('tourID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.TOURINFO')),
            ],
        ),
        migrations.CreateModel(
            name='TOURINFOACTIVITY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.ACTIVITY')),
                ('tourID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.TOURINFO')),
            ],
        ),
        migrations.CreateModel(
            name='SPOTPREFERENCE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='allImages/')),
                ('preferenceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.PREFERENCE')),
                ('spotID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.SPOT')),
            ],
        ),
        migrations.CreateModel(
            name='SPOTACTIVITY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='allImages/')),
                ('activityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.ACTIVITY')),
                ('spotID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.SPOT')),
            ],
        ),
        migrations.CreateModel(
            name='PROFILEGROUP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.GROUP')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.PROFILE')),
            ],
        ),
        migrations.CreateModel(
            name='PREFERENCETOURINFO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferenceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.PREFERENCE')),
                ('tourID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.TOURINFO')),
            ],
        ),
        migrations.CreateModel(
            name='HOTELTOURINFO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotelID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.HOTEL')),
                ('tourID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.TOURINFO')),
            ],
        ),
        migrations.CreateModel(
            name='GUIDETOURINFO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guideID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.PROFILE')),
                ('tourID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.TOURINFO')),
            ],
        ),
        migrations.CreateModel(
            name='CITYTOURINFO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.CITY')),
                ('tourID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.TOURINFO')),
            ],
        ),
        migrations.CreateModel(
            name='CITYPROFILE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.CITY')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.PROFILE')),
            ],
        ),
        migrations.CreateModel(
            name='CITYPREFERENCE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.CITY')),
                ('preferenceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.PREFERENCE')),
            ],
        ),
        migrations.CreateModel(
            name='BLOG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogCaption', models.CharField(max_length=200)),
                ('blogPostDate', models.DateField(auto_now_add=True)),
                ('blogData', models.CharField(max_length=2000)),
                ('image', models.ImageField(default='noimage.jpg', upload_to='allImages/')),
                ('userID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.PROFILE')),
            ],
        ),
    ]
