# Generated by Django 2.2.1 on 2019-08-23 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20190721_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='GROUPMESSAGE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=50)),
                ('message', models.CharField(blank=True, max_length=1000)),
                ('time', models.CharField(blank=True, max_length=50)),
                ('groupID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.GROUP')),
            ],
        ),
    ]
